#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

ROOT_DIR="$( dirname $( dirname "${DIR}" ) )"

arduino-cli compile \
  --fqbn arduino:avr:nano \
  --format json \
  ${ROOT_DIR}
